version: "3.9"

services:
  php:
    user: "${UID}:${GID}"
    container_name: php-alpine-development
    hostname: php-alpine-development
    image: mikel00per/php-alpine-development
    env_file:
      - ./api/.env
    ports:
      - "9000:9000"
    volumes:
      - ./api:/code
    links:
      - nginx

  nginx:
    image: mikel00per/nginx-alpine-development
    ports:
      - "80:80"
