name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Copy env
        run: cp api/.env.example api/.env

      - name: Run containers
        run: make run

      - name: Check tests
        run: make test

      - name: Check access
        run: make test-integration
